### ISSUE TITLE
Support for multiple dex files

### ISSUE THREAD

**Issue by matejdro** [Furniel/Apk-Changer#12]
Nowadays apps are huge and many of them have multiple dex files (`classes.dex`, `classes2.dex` etc.).

It appears that Apk-Changer does not support this at all at the moment (it only decompiles/compiles original `classes.dex`, but completely ignores all subsequent classes).

Example huge app that does not properly decompile/recompile: http://www.apkmirror.com/apk/spotify-ltd/spotify/spotify-7-4-0-1799-release/

**Comment by Furniel** [comment]
Hello. Are you using latest version of apk-changer? Your bug report is strange because classes2.dex support was added by this commit https://github.com/Furniel/Apk-Changer/commit/2c06dc7993a910b3fd45e00b6a1ecfc4f726cfac in Jul 21, 2014. Later was added support for more dex files and now apk-changer supports unlimited number of classes.dex(some samsung apps have up to 30 classes and all will be decompiled). So may be you are using really outdated version or there is some bug and that's why classes2 and so on are not decompiled(if so can you tell what version of windows you use(version, architecture and locale) and maybe there are some errors in log?). I usually test apk-changer on english win 10 x64, sometimes on english win 7 x 64 and russian win 7 x32.
PS: tested spotify-7-4-0-1799 and spotify-7.5.0.1076 both apk's were successfully decompiled.

**Comment by matejdro** [comment]
After testing this issue some more, it appears it only applies if I want to only decompile the sources.  If I decompile everything (sources + resources), it works fine.

**Comment by Furniel** [comment]
Need to fix one more thing, found real reason of this bug.
